### ISSUE TITLE
Some feed reader not recognizing Atom feed article URIs

### ISSUE THREAD

**Issue by supermomonga** [mayuki/WeekRef.NET#136]
My feed reader app doesn't recognize the URI of each article.

I dug into the ATOM feed specifications and found that maybe the `atom:link` element's `href` attribute should probably contain IRIs as defined in RFC3987.

https://datatracker.ietf.org/doc/html/rfc4287#section-4.2.7
https://datatracker.ietf.org/doc/html/rfc3987

Currently, I think the Atom feed only contains article path, not URI.

e.g.)

```xml
<entry>
  <id>/2024/06/14/updates</id>
  <title>2024-06-14: .NET MAUI Extension for VS Code, Windows App SDK 1.5.4, .NET 9 Preview 5</title>
  <author>
    <name>Mayuki Sawatari</name>
  </author>
  <link href="/2024/06/14/updates" />
  <link rel="enclosure" type="image" href="/img/logo.png" />
  <updated>2024-06-14T00:00:00Z</updated>
  <content>...</content>
  <summary>.NET 関連の情報をほぼ週刊配信</summary>
</entry>
```

**Comment by mayuki** [comment]
I am very sorry for the delay, but I have found that it can be corrected by changing the settings, so I have addressed the issue. 

Thank you for your feedback!

**Comment by supermomonga** [comment]
@mayuki Thanks a lot! it works perfectly in my feedreader.
